name: build
on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '11'
            -   name: maven build
                run: mvn --batch-mode --errors --show-version --no-transfer-progress clean verify
